name: weto
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - dask
  - dask-jobqueue
  - descartes
  - distributed
  - geopandas
  - gdal=2.4.4
  - h5py
  - matplotlib
  - netcdf4
  - rasterio
  - scipy
  - spyder
  - tqdm
