name: weto
channels:
  - conda-forge
dependencies:
  - python=3.7
  - dask
  - descartes
  - distributed
  - geopandas
  - gdal
  - h5py
  - matplotlib
  - scipy
  - spyder
  - tqdm
  - pip:
    - "--editable=git+https://github.nrel.gov/GDS/pygds.git"
    - geofeather
