name: weto
channels:
  - conda-forge
dependencies:
  - python=3.7
  - dask
  - dask-jobqueue
  - descartes
  - distributed
  - geopandas
  - gdal
  - h5py
  - matplotlib
  - rioxarray
  - scipy
  - spyder
  - tqdm
